#http://localhost:8080/api/easycars/swagger-ui/index.html?configUrl=/api/easycars/v3/api-docs/swagger-config#/vehicle-controller/save
#localhost:8080/api/easycars/h2-console/
server:
  port: 8080
  servlet:
    context-path: /api/easycars
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:easycars_db
    password: ''
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
